# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rasterizeLayer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_rasterizeLayer(object):
    def setupUi(self, Dialog_rasterizeLayer):
        Dialog_rasterizeLayer.setObjectName("Dialog_rasterizeLayer")
        Dialog_rasterizeLayer.resize(492, 292)
        self.widget = QtWidgets.QWidget(Dialog_rasterizeLayer)
        self.widget.setGeometry(QtCore.QRect(21, 13, 461, 187))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_imgpath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_imgpath.setObjectName("lineEdit_imgpath")
        self.horizontalLayout_4.addWidget(self.lineEdit_imgpath)
        self.pushButton_imagepath = QtWidgets.QPushButton(self.widget)
        self.pushButton_imagepath.setObjectName("pushButton_imagepath")
        self.horizontalLayout_4.addWidget(self.pushButton_imagepath)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(456, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.lineEdit_shpfilepath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_shpfilepath.setObjectName("lineEdit_shpfilepath")
        self.horizontalLayout_3.addWidget(self.lineEdit_shpfilepath)
        self.pushButton_shpfilepath = QtWidgets.QPushButton(self.widget)
        self.pushButton_shpfilepath.setObjectName("pushButton_shpfilepath")
        self.horizontalLayout_3.addWidget(self.pushButton_shpfilepath)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(456, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_outputpath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_outputpath.setObjectName("lineEdit_outputpath")
        self.horizontalLayout_2.addWidget(self.lineEdit_outputpath)
        self.pushButton_outputpath = QtWidgets.QPushButton(self.widget)
        self.pushButton_outputpath.setObjectName("pushButton_outputpath")
        self.horizontalLayout_2.addWidget(self.pushButton_outputpath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(456, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_attributeFiledName = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_attributeFiledName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_attributeFiledName.setObjectName("lineEdit_attributeFiledName")
        self.horizontalLayout.addWidget(self.lineEdit_attributeFiledName)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog_rasterizeLayer)
        self.buttonBox.accepted.connect(Dialog_rasterizeLayer.slot_ok)
        self.buttonBox.rejected.connect(Dialog_rasterizeLayer.reject)
        self.pushButton_imagepath.clicked.connect(Dialog_rasterizeLayer.slot_select_imgpath)
        self.pushButton_shpfilepath.clicked.connect(Dialog_rasterizeLayer.slot_select_shpfilepath)
        self.pushButton_outputpath.clicked.connect(Dialog_rasterizeLayer.slot_select_outputpath)
        QtCore.QMetaObject.connectSlotsByName(Dialog_rasterizeLayer)

    def retranslateUi(self, Dialog_rasterizeLayer):
        _translate = QtCore.QCoreApplication.translate
        Dialog_rasterizeLayer.setWindowTitle(_translate("Dialog_rasterizeLayer", "Dialog"))
        self.label_5.setText(_translate("Dialog_rasterizeLayer", "imageFile"))
        self.pushButton_imagepath.setText(_translate("Dialog_rasterizeLayer", "open"))
        self.label_11.setText(_translate("Dialog_rasterizeLayer", "shpFile"))
        self.pushButton_shpfilepath.setText(_translate("Dialog_rasterizeLayer", "open"))
        self.label_6.setText(_translate("Dialog_rasterizeLayer", "outputFile"))
        self.pushButton_outputpath.setText(_translate("Dialog_rasterizeLayer", "open"))
        self.label_4.setText(_translate("Dialog_rasterizeLayer", "attributeFiledName"))
        self.lineEdit_attributeFiledName.setText(_translate("Dialog_rasterizeLayer", "DN"))
