# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'Dialog_train.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_Dialog_train(object):
    def setupUi(self, Dialog_train):
        Dialog_train.setObjectName("Dialog_train")
        Dialog_train.resize(500, 300)
        Dialog_train.setMinimumSize(QtCore.QSize(458, 256))
        Dialog_train.setMaximumSize(QtCore.QSize(500, 300))
        self.layoutWidget = QtWidgets.QWidget(Dialog_train)
        self.layoutWidget.setGeometry(QtCore.QRect(55, 220, 401, 34))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(42, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_gpuid = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_gpuid.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_gpuid.setFont(font)
        self.comboBox_gpuid.setObjectName("comboBox_gpuid")
        self.comboBox_gpuid.addItem("")
        self.comboBox_gpuid.addItem("")
        self.comboBox_gpuid.addItem("")
        self.comboBox_gpuid.addItem("")
        self.comboBox_gpuid.addItem("")
        self.comboBox_gpuid.addItem("")
        self.comboBox_gpuid.addItem("")
        self.comboBox_gpuid.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_gpuid)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.widget = QtWidgets.QWidget(Dialog_train)
        self.widget.setGeometry(QtCore.QRect(31, 20, 411, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(45, 0))
        self.label.setMaximumSize(QtCore.QSize(333333, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_sample = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_sample.setFont(font)
        self.lineEdit_sample.setObjectName("lineEdit_sample")
        self.horizontalLayout.addWidget(self.lineEdit_sample)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(45, 0))
        self.label_2.setMaximumSize(QtCore.QSize(44444, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_config = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_config.setMaximumSize(QtCore.QSize(265, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_config.setFont(font)
        self.lineEdit_config.setObjectName("lineEdit_config")
        self.horizontalLayout_2.addWidget(self.lineEdit_config)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setEnabled(True)
        self.label_3.setMinimumSize(QtCore.QSize(45, 0))
        self.label_3.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_modelpath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_modelpath.setMaximumSize(QtCore.QSize(265, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_modelpath.setFont(font)
        self.lineEdit_modelpath.setObjectName("lineEdit_modelpath")
        self.horizontalLayout_3.addWidget(self.lineEdit_modelpath)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog_train)
        self.buttonBox.rejected.connect(Dialog_train.reject)
        self.buttonBox.accepted.connect(Dialog_train.slot_process)
        self.pushButton.clicked.connect(Dialog_train.slot_open_sample)
        self.pushButton_4.clicked.connect(Dialog_train.slot_open_modelpath)
        self.pushButton_2.clicked.connect(Dialog_train.slot_open_config)
        QtCore.QMetaObject.connectSlotsByName(Dialog_train)

    def retranslateUi(self, Dialog_train):
        _translate = QtCore.QCoreApplication.translate
        Dialog_train.setWindowTitle(_translate("Dialog_train", "Dialog"))
        self.label_4.setText(_translate("Dialog_train", "GPU ID:"))
        self.comboBox_gpuid.setItemText(0, _translate("Dialog_train", "0"))
        self.comboBox_gpuid.setItemText(1, _translate("Dialog_train", "1"))
        self.comboBox_gpuid.setItemText(2, _translate("Dialog_train", "2"))
        self.comboBox_gpuid.setItemText(3, _translate("Dialog_train", "3"))
        self.comboBox_gpuid.setItemText(4, _translate("Dialog_train", "4"))
        self.comboBox_gpuid.setItemText(5, _translate("Dialog_train", "5"))
        self.comboBox_gpuid.setItemText(6, _translate("Dialog_train", "6"))
        self.comboBox_gpuid.setItemText(7, _translate("Dialog_train", "7"))
        self.label.setText(_translate("Dialog_train", "Sample"))
        self.pushButton.setText(_translate("Dialog_train", "open"))
        self.label_2.setText(_translate("Dialog_train", "Config"))
        self.pushButton_2.setText(_translate("Dialog_train", "open"))
        self.label_3.setText(_translate("Dialog_train", "Model"))
        self.pushButton_4.setText(_translate("Dialog_train", "open"))
