# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crfui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_crf(object):
    def setupUi(self, Dialog_crf):
        Dialog_crf.setObjectName("Dialog_crf")
        Dialog_crf.resize(578, 451)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_crf)
        self.buttonBox.setGeometry(QtCore.QRect(170, 410, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog_crf)
        self.groupBox.setGeometry(QtCore.QRect(20, 180, 137, 66))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.doubleSpinBox_gtprob = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_gtprob.setMinimumSize(QtCore.QSize(59, 23))
        self.doubleSpinBox_gtprob.setMaximum(1.0)
        self.doubleSpinBox_gtprob.setSingleStep(0.1)
        self.doubleSpinBox_gtprob.setProperty("value", 0.9)
        self.doubleSpinBox_gtprob.setObjectName("doubleSpinBox_gtprob")
        self.gridLayout.addWidget(self.doubleSpinBox_gtprob, 0, 1, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_crf)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 260, 540, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.spinBox_gauss_sxy = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_gauss_sxy.setMinimumSize(QtCore.QSize(0, 23))
        self.spinBox_gauss_sxy.setMinimum(1)
        self.spinBox_gauss_sxy.setMaximum(1000)
        self.spinBox_gauss_sxy.setSingleStep(5)
        self.spinBox_gauss_sxy.setProperty("value", 5)
        self.spinBox_gauss_sxy.setObjectName("spinBox_gauss_sxy")
        self.horizontalLayout_8.addWidget(self.spinBox_gauss_sxy)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.spinBox_gauss_compat = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.spinBox_gauss_compat.sizePolicy().hasHeightForWidth())
        self.spinBox_gauss_compat.setSizePolicy(sizePolicy)
        self.spinBox_gauss_compat.setMinimumSize(QtCore.QSize(78, 23))
        self.spinBox_gauss_compat.setMinimum(3)
        self.spinBox_gauss_compat.setMaximum(1000)
        self.spinBox_gauss_compat.setSingleStep(2)
        self.spinBox_gauss_compat.setProperty("value", 5)
        self.spinBox_gauss_compat.setObjectName("spinBox_gauss_compat")
        self.horizontalLayout_12.addWidget(self.spinBox_gauss_compat)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.spinBox_bilateral_sxy = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_bilateral_sxy.setMinimumSize(QtCore.QSize(0, 23))
        self.spinBox_bilateral_sxy.setMinimum(4)
        self.spinBox_bilateral_sxy.setMaximum(1000)
        self.spinBox_bilateral_sxy.setSingleStep(2)
        self.spinBox_bilateral_sxy.setProperty("value", 10)
        self.spinBox_bilateral_sxy.setObjectName("spinBox_bilateral_sxy")
        self.horizontalLayout_9.addWidget(self.spinBox_bilateral_sxy)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.spinBox_bilateral_srgb = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.spinBox_bilateral_srgb.sizePolicy().hasHeightForWidth())
        self.spinBox_bilateral_srgb.setSizePolicy(sizePolicy)
        self.spinBox_bilateral_srgb.setMinimumSize(QtCore.QSize(78, 23))
        self.spinBox_bilateral_srgb.setMinimum(3)
        self.spinBox_bilateral_srgb.setMaximum(1000)
        self.spinBox_bilateral_srgb.setSingleStep(2)
        self.spinBox_bilateral_srgb.setProperty("value", 13)
        self.spinBox_bilateral_srgb.setObjectName("spinBox_bilateral_srgb")
        self.horizontalLayout_10.addWidget(self.spinBox_bilateral_srgb)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.spinBox_bilateral_compat = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.spinBox_bilateral_compat.sizePolicy().hasHeightForWidth())
        self.spinBox_bilateral_compat.setSizePolicy(sizePolicy)
        self.spinBox_bilateral_compat.setMinimumSize(QtCore.QSize(78, 23))
        self.spinBox_bilateral_compat.setMinimum(3)
        self.spinBox_bilateral_compat.setMaximum(1000)
        self.spinBox_bilateral_compat.setSingleStep(2)
        self.spinBox_bilateral_compat.setProperty("value", 10)
        self.spinBox_bilateral_compat.setObjectName("spinBox_bilateral_compat")
        self.horizontalLayout_11.addWidget(self.spinBox_bilateral_compat)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_2)
        self.widget = QtWidgets.QWidget(Dialog_crf)
        self.widget.setGeometry(QtCore.QRect(21, 21, 541, 138))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_input_img = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_input_img.setObjectName("lineEdit_input_img")
        self.horizontalLayout.addWidget(self.lineEdit_input_img)
        self.pushButton_select_input_img = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_input_img.setObjectName("pushButton_select_input_img")
        self.horizontalLayout.addWidget(self.pushButton_select_input_img)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_input_mask = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_input_mask.setObjectName("lineEdit_input_mask")
        self.horizontalLayout_7.addWidget(self.lineEdit_input_mask)
        self.pushButton_select_input_mask = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_input_mask.setObjectName("pushButton_select_input_mask")
        self.horizontalLayout_7.addWidget(self.pushButton_select_input_mask)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_result = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.horizontalLayout_3.addWidget(self.lineEdit_result)
        self.pushButton_select_outputdir = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_outputdir.setObjectName("pushButton_select_outputdir")
        self.horizontalLayout_3.addWidget(self.pushButton_select_outputdir)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog_crf)
        self.buttonBox.accepted.connect(Dialog_crf.slot_ok)
        self.buttonBox.rejected.connect(Dialog_crf.reject)
        self.pushButton_select_input_img.clicked.connect(Dialog_crf.slot_input_img)
        self.pushButton_select_input_mask.clicked.connect(Dialog_crf.slot_input_mask)
        self.pushButton_select_outputdir.clicked.connect(Dialog_crf.slot_result_save)
        QtCore.QMetaObject.connectSlotsByName(Dialog_crf)

    def retranslateUi(self, Dialog_crf):
        _translate = QtCore.QCoreApplication.translate
        Dialog_crf.setWindowTitle(_translate("Dialog_crf", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog_crf", "Unary potential"))
        self.label_4.setText(_translate("Dialog_crf", "gtProb"))
        self.groupBox_2.setTitle(_translate("Dialog_crf", "Pairwise potentials"))
        self.label_2.setText(_translate("Dialog_crf", "Gausssian:"))
        self.label_7.setText(_translate("Dialog_crf", "sxy"))
        self.label_11.setText(_translate("Dialog_crf", "compat"))
        self.label_5.setText(_translate("Dialog_crf", "Bilateral :"))
        self.label_8.setText(_translate("Dialog_crf", "sxy"))
        self.label_9.setText(_translate("Dialog_crf", "srgb"))
        self.label_10.setText(_translate("Dialog_crf", "compat"))
        self.label.setText(_translate("Dialog_crf", "image"))
        self.pushButton_select_input_img.setText(_translate("Dialog_crf", "open"))
        self.label_6.setText(_translate("Dialog_crf", "mask"))
        self.pushButton_select_input_mask.setText(_translate("Dialog_crf", "open"))
        self.label_3.setText(_translate("Dialog_crf", "result"))
        self.pushButton_select_outputdir.setText(_translate("Dialog_crf", "open"))

