# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removeSmallPolygon.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_removeSmallPolygon(object):
    def setupUi(self, Dialog_removeSmallPolygon):
        Dialog_removeSmallPolygon.setObjectName("Dialog_removeSmallPolygon")
        Dialog_removeSmallPolygon.resize(488, 231)
        self.layoutWidget = QtWidgets.QWidget(Dialog_removeSmallPolygon)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 421, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_inputdir = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_inputdir.setObjectName("lineEdit_inputdir")
        self.horizontalLayout.addWidget(self.lineEdit_inputdir)
        self.pushButton_select_inputdir = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_select_inputdir.setObjectName("pushButton_select_inputdir")
        self.horizontalLayout.addWidget(self.pushButton_select_inputdir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_outputdir = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_outputdir.setObjectName("lineEdit_outputdir")
        self.horizontalLayout_3.addWidget(self.lineEdit_outputdir)
        self.pushButton_select_outputdir = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_select_outputdir.setObjectName("pushButton_select_outputdir")
        self.horizontalLayout_3.addWidget(self.pushButton_select_outputdir)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_removeSmallPolygon)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 160, 337, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_scale = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_scale.setObjectName("comboBox_scale")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_scale)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget1)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_removeSmallPolygon)
        self.buttonBox.accepted.connect(Dialog_removeSmallPolygon.slot_ok)
        self.buttonBox.rejected.connect(Dialog_removeSmallPolygon.reject)
        self.pushButton_select_inputdir.clicked.connect(Dialog_removeSmallPolygon.slot_select_inputdir)
        self.pushButton_select_outputdir.clicked.connect(Dialog_removeSmallPolygon.slot_select_outputdir)
        QtCore.QMetaObject.connectSlotsByName(Dialog_removeSmallPolygon)

    def retranslateUi(self, Dialog_removeSmallPolygon):
        _translate = QtCore.QCoreApplication.translate
        Dialog_removeSmallPolygon.setWindowTitle(_translate("Dialog_removeSmallPolygon", "removeSmallPolygon"))
        self.label.setText(_translate("Dialog_removeSmallPolygon", "input_dir"))
        self.pushButton_select_inputdir.setText(_translate("Dialog_removeSmallPolygon", "open"))
        self.label_3.setText(_translate("Dialog_removeSmallPolygon", "output_dir"))
        self.pushButton_select_outputdir.setText(_translate("Dialog_removeSmallPolygon", "open"))
        self.label_2.setText(_translate("Dialog_removeSmallPolygon", "pixel_scale"))
        self.comboBox_scale.setCurrentText(_translate("Dialog_removeSmallPolygon", "1"))
        self.comboBox_scale.setItemText(0, _translate("Dialog_removeSmallPolygon", "1"))
        self.comboBox_scale.setItemText(1, _translate("Dialog_removeSmallPolygon", "2"))
        self.comboBox_scale.setItemText(2, _translate("Dialog_removeSmallPolygon", "3"))
        self.comboBox_scale.setItemText(3, _translate("Dialog_removeSmallPolygon", "4"))
        self.comboBox_scale.setItemText(4, _translate("Dialog_removeSmallPolygon", "5"))
        self.comboBox_scale.setItemText(5, _translate("Dialog_removeSmallPolygon", "6"))
        self.comboBox_scale.setItemText(6, _translate("Dialog_removeSmallPolygon", "7"))
        self.comboBox_scale.setItemText(7, _translate("Dialog_removeSmallPolygon", "8"))
        self.comboBox_scale.setItemText(8, _translate("Dialog_removeSmallPolygon", "9"))
