# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removeSmallPolygon.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_removeSmallPolygon(object):
    def setupUi(self, Dialog_removeSmallPolygon):
        Dialog_removeSmallPolygon.setObjectName("Dialog_removeSmallPolygon")
        Dialog_removeSmallPolygon.resize(499, 244)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_removeSmallPolygon)
        self.buttonBox.setGeometry(QtCore.QRect(290, 200, 166, 22))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_removeSmallPolygon)
        self.widget.setGeometry(QtCore.QRect(10, 20, 465, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_inputdir = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_inputdir.setObjectName("lineEdit_inputdir")
        self.horizontalLayout.addWidget(self.lineEdit_inputdir)
        self.pushButton_select_inputdir = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_inputdir.setObjectName("pushButton_select_inputdir")
        self.horizontalLayout.addWidget(self.pushButton_select_inputdir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_outputdir = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_outputdir.setObjectName("lineEdit_outputdir")
        self.horizontalLayout_3.addWidget(self.lineEdit_outputdir)
        self.pushButton_select_outputdir = QtWidgets.QPushButton(self.widget)
        self.pushButton_select_outputdir.setObjectName("pushButton_select_outputdir")
        self.horizontalLayout_3.addWidget(self.pushButton_select_outputdir)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.checkBox_flag = QtWidgets.QCheckBox(self.widget)
        self.checkBox_flag.setChecked(True)
        self.checkBox_flag.setObjectName("checkBox_flag")
        self.horizontalLayout_2.addWidget(self.checkBox_flag)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox_ms = QtWidgets.QSpinBox(self.widget)
        self.spinBox_ms.setMinimumSize(QtCore.QSize(0, 23))
        self.spinBox_ms.setMinimum(1)
        self.spinBox_ms.setMaximum(1000)
        self.spinBox_ms.setSingleStep(5)
        self.spinBox_ms.setProperty("value", 5)
        self.spinBox_ms.setObjectName("spinBox_ms")
        self.horizontalLayout_4.addWidget(self.spinBox_ms)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_thd = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.spinBox_thd.sizePolicy().hasHeightForWidth())
        self.spinBox_thd.setSizePolicy(sizePolicy)
        self.spinBox_thd.setMinimumSize(QtCore.QSize(78, 23))
        self.spinBox_thd.setMinimum(1)
        self.spinBox_thd.setMaximum(100000)
        self.spinBox_thd.setSingleStep(100)
        self.spinBox_thd.setProperty("value", 100)
        self.spinBox_thd.setObjectName("spinBox_thd")
        self.horizontalLayout_5.addWidget(self.spinBox_thd)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog_removeSmallPolygon)
        self.buttonBox.accepted.connect(Dialog_removeSmallPolygon.slot_ok)
        self.buttonBox.rejected.connect(Dialog_removeSmallPolygon.reject)
        self.pushButton_select_inputdir.clicked.connect(Dialog_removeSmallPolygon.slot_select_inputdir)
        self.pushButton_select_outputdir.clicked.connect(Dialog_removeSmallPolygon.slot_select_outputdir)
        QtCore.QMetaObject.connectSlotsByName(Dialog_removeSmallPolygon)

    def retranslateUi(self, Dialog_removeSmallPolygon):
        _translate = QtCore.QCoreApplication.translate
        Dialog_removeSmallPolygon.setWindowTitle(_translate("Dialog_removeSmallPolygon", "消除小面"))
        self.label.setText(_translate("Dialog_removeSmallPolygon", "input_dir"))
        self.pushButton_select_inputdir.setText(_translate("Dialog_removeSmallPolygon", "open"))
        self.label_3.setText(_translate("Dialog_removeSmallPolygon", "output_dir"))
        self.pushButton_select_outputdir.setText(_translate("Dialog_removeSmallPolygon", "open"))
        self.label_4.setText(_translate("Dialog_removeSmallPolygon", "method"))
        self.checkBox_flag.setText(_translate("Dialog_removeSmallPolygon", "CV"))
        self.label_2.setText(_translate("Dialog_removeSmallPolygon", "minsize"))
        self.label_5.setText(_translate("Dialog_removeSmallPolygon", "threshold"))

