# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_predict.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_predict(object):
    def setupUi(self, Dialog_predict):
        Dialog_predict.setObjectName("Dialog_predict")
        Dialog_predict.resize(492, 252)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_predict)
        self.buttonBox.setGeometry(QtCore.QRect(290, 210, 181, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_predict)
        self.layoutWidget.setGeometry(QtCore.QRect(156, 210, 81, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_gpu = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.comboBox_gpu.setFont(font)
        self.comboBox_gpu.setObjectName("comboBox_gpu")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_gpu)
        self.widget = QtWidgets.QWidget(Dialog_predict)
        self.widget.setGeometry(QtCore.QRect(30, 10, 431, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_input = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_input.setFont(font)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.BT_input = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.BT_input.setFont(font)
        self.BT_input.setObjectName("BT_input")
        self.horizontalLayout.addWidget(self.BT_input)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_output = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_output.setFont(font)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_2.addWidget(self.lineEdit_output)
        self.BT_output = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.BT_output.setFont(font)
        self.BT_output.setObjectName("BT_output")
        self.horizontalLayout_2.addWidget(self.BT_output)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_config = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_config.setFont(font)
        self.lineEdit_config.setObjectName("lineEdit_config")
        self.horizontalLayout_3.addWidget(self.lineEdit_config)
        self.BT_config = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.BT_config.setFont(font)
        self.BT_config.setObjectName("BT_config")
        self.horizontalLayout_3.addWidget(self.BT_config)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.lineEdit_model = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_model.setFont(font)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.horizontalLayout_5.addWidget(self.lineEdit_model)
        self.BT_model = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.BT_model.setFont(font)
        self.BT_model.setObjectName("BT_model")
        self.horizontalLayout_5.addWidget(self.BT_model)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog_predict)
        self.buttonBox.rejected.connect(Dialog_predict.reject)
        self.BT_input.clicked.connect(Dialog_predict.slot_input)
        self.BT_output.clicked.connect(Dialog_predict.slot_output)
        self.BT_config.clicked.connect(Dialog_predict.slot_config)
        self.buttonBox.accepted.connect(Dialog_predict.slot_done)
        self.BT_model.clicked.connect(Dialog_predict.slot_model)
        QtCore.QMetaObject.connectSlotsByName(Dialog_predict)

    def retranslateUi(self, Dialog_predict):
        _translate = QtCore.QCoreApplication.translate
        Dialog_predict.setWindowTitle(_translate("Dialog_predict", "Dialog"))
        self.label_4.setText(_translate("Dialog_predict", "GPU"))
        self.comboBox_gpu.setItemText(0, _translate("Dialog_predict", "0"))
        self.comboBox_gpu.setItemText(1, _translate("Dialog_predict", "1"))
        self.comboBox_gpu.setItemText(2, _translate("Dialog_predict", "2"))
        self.comboBox_gpu.setItemText(3, _translate("Dialog_predict", "3"))
        self.comboBox_gpu.setItemText(4, _translate("Dialog_predict", "4"))
        self.comboBox_gpu.setItemText(5, _translate("Dialog_predict", "5"))
        self.comboBox_gpu.setItemText(6, _translate("Dialog_predict", "6"))
        self.comboBox_gpu.setItemText(7, _translate("Dialog_predict", "7"))
        self.label.setText(_translate("Dialog_predict", "input"))
        self.BT_input.setText(_translate("Dialog_predict", "Open"))
        self.label_2.setText(_translate("Dialog_predict", "output"))
        self.BT_output.setText(_translate("Dialog_predict", "Open"))
        self.label_3.setText(_translate("Dialog_predict", "config"))
        self.BT_config.setText(_translate("Dialog_predict", "Open"))
        self.label_5.setText(_translate("Dialog_predict", "model"))
        self.BT_model.setText(_translate("Dialog_predict", "Open"))
