# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predict_one.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_predict_one(object):
    def setupUi(self, Dialog_predict_one):
        Dialog_predict_one.setObjectName("Dialog_predict_one")
        Dialog_predict_one.resize(492, 246)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_predict_one)
        self.buttonBox.setGeometry(QtCore.QRect(130, 190, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_predict_one)
        self.widget.setGeometry(QtCore.QRect(11, 11, 463, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_input = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.pushButton_input = QtWidgets.QPushButton(self.widget)
        self.pushButton_input.setObjectName("pushButton_input")
        self.horizontalLayout.addWidget(self.pushButton_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_gpu = QtWidgets.QComboBox(self.widget)
        self.comboBox_gpu.setObjectName("comboBox_gpu")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_gpu)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_config = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_config.setMinimumSize(QtCore.QSize(220, 1))
        self.lineEdit_config.setObjectName("lineEdit_config")
        self.horizontalLayout_3.addWidget(self.lineEdit_config)
        self.pushButton_config = QtWidgets.QPushButton(self.widget)
        self.pushButton_config.setObjectName("pushButton_config")
        self.horizontalLayout_3.addWidget(self.pushButton_config)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_model = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.horizontalLayout_6.addWidget(self.lineEdit_model)
        self.pushButton_model = QtWidgets.QPushButton(self.widget)
        self.pushButton_model.setObjectName("pushButton_model")
        self.horizontalLayout_6.addWidget(self.pushButton_model)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_output = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_2.addWidget(self.lineEdit_output)
        self.pushButton_output = QtWidgets.QPushButton(self.widget)
        self.pushButton_output.setObjectName("pushButton_output")
        self.horizontalLayout_2.addWidget(self.pushButton_output)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_predict_one)
        self.buttonBox.rejected.connect(Dialog_predict_one.reject)
        self.pushButton_input.clicked.connect(Dialog_predict_one.slot_input)
        self.pushButton_config.clicked.connect(Dialog_predict_one.slot_config)
        self.pushButton_output.clicked.connect(Dialog_predict_one.slot_output)
        self.buttonBox.accepted.connect(Dialog_predict_one.slot_ok)
        self.pushButton_model.clicked.connect(Dialog_predict_one.slot_model)
        QtCore.QMetaObject.connectSlotsByName(Dialog_predict_one)

    def retranslateUi(self, Dialog_predict_one):
        _translate = QtCore.QCoreApplication.translate
        Dialog_predict_one.setWindowTitle(_translate("Dialog_predict_one", "Dialog"))
        self.label.setText(_translate("Dialog_predict_one", "Input"))
        self.pushButton_input.setText(_translate("Dialog_predict_one", "Open"))
        self.label_4.setText(_translate("Dialog_predict_one", "GPU"))
        self.comboBox_gpu.setItemText(0, _translate("Dialog_predict_one", "0"))
        self.comboBox_gpu.setItemText(1, _translate("Dialog_predict_one", "1"))
        self.comboBox_gpu.setItemText(2, _translate("Dialog_predict_one", "2"))
        self.comboBox_gpu.setItemText(3, _translate("Dialog_predict_one", "3"))
        self.comboBox_gpu.setItemText(4, _translate("Dialog_predict_one", "4"))
        self.comboBox_gpu.setItemText(5, _translate("Dialog_predict_one", "5"))
        self.label_3.setText(_translate("Dialog_predict_one", "Config"))
        self.pushButton_config.setText(_translate("Dialog_predict_one", "Open"))
        self.label_5.setText(_translate("Dialog_predict_one", "Model"))
        self.pushButton_model.setText(_translate("Dialog_predict_one", "Open"))
        self.label_2.setText(_translate("Dialog_predict_one", "Result"))
        self.pushButton_output.setText(_translate("Dialog_predict_one", "Open"))

