# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sample2H5.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_sample2H5(object):
    def setupUi(self, Dialog_sample2H5):
        Dialog_sample2H5.setObjectName("Dialog_sample2H5")
        Dialog_sample2H5.resize(431, 337)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_sample2H5)
        self.buttonBox.setGeometry(QtCore.QRect(240, 290, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_sample2H5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(55, 23))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_input.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.pushButton_input = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_input.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_input.setObjectName("pushButton_input")
        self.horizontalLayout.addWidget(self.pushButton_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 66))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.doubleSpinBox_val_rate = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_val_rate.setMinimum(0.05)
        self.doubleSpinBox_val_rate.setMaximum(0.6)
        self.doubleSpinBox_val_rate.setSingleStep(0.05)
        self.doubleSpinBox_val_rate.setProperty("value", 0.25)
        self.doubleSpinBox_val_rate.setObjectName("doubleSpinBox_val_rate")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_val_rate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.comboBox_mode = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_mode)
        self.horizontalLayout_11.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(55, 23))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.lineEdit_output = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_output.setMinimumSize(QtCore.QSize(201, 23))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_15.addWidget(self.lineEdit_output)
        self.pushButton_output = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_output.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_output.setObjectName("pushButton_output")
        self.horizontalLayout_15.addWidget(self.pushButton_output)
        self.verticalLayout.addLayout(self.horizontalLayout_15)

        self.retranslateUi(Dialog_sample2H5)
        self.buttonBox.accepted.connect(Dialog_sample2H5.slot_ok)
        self.buttonBox.rejected.connect(Dialog_sample2H5.reject)
        self.pushButton_input.clicked.connect(Dialog_sample2H5.slot_input)
        self.pushButton_output.clicked.connect(Dialog_sample2H5.slot_output)
        QtCore.QMetaObject.connectSlotsByName(Dialog_sample2H5)

    def retranslateUi(self, Dialog_sample2H5):
        _translate = QtCore.QCoreApplication.translate
        Dialog_sample2H5.setWindowTitle(_translate("Dialog_sample2H5", "Convert samples to h5"))
        self.label.setText(_translate("Dialog_sample2H5", "Input Dir"))
        self.pushButton_input.setText(_translate("Dialog_sample2H5", "Open"))
        self.groupBox_4.setTitle(_translate("Dialog_sample2H5", "Strategy"))
        self.label_3.setText(_translate("Dialog_sample2H5", "Valid data rate"))
        self.label_2.setText(_translate("Dialog_sample2H5", "Src date mode"))
        self.comboBox_mode.setItemText(0, _translate("Dialog_sample2H5", "UINT8"))
        self.comboBox_mode.setItemText(1, _translate("Dialog_sample2H5", "UINT16"))
        self.label_6.setText(_translate("Dialog_sample2H5", "Save Path"))
        self.pushButton_output.setText(_translate("Dialog_sample2H5", "Open"))
