# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_predict.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_predict(object):
    def setupUi(self, Dialog_predict):
        Dialog_predict.setObjectName("Dialog_predict")
        Dialog_predict.resize(492, 252)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_predict)
        self.buttonBox.setGeometry(QtCore.QRect(290, 210, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_predict)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 441, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.BT_input = QtWidgets.QPushButton(self.layoutWidget)
        self.BT_input.setObjectName("BT_input")
        self.horizontalLayout.addWidget(self.BT_input)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_predict)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 60, 441, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_output = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_2.addWidget(self.lineEdit_output)
        self.BT_output = QtWidgets.QPushButton(self.layoutWidget1)
        self.BT_output.setObjectName("BT_output")
        self.horizontalLayout_2.addWidget(self.BT_output)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog_predict)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 100, 441, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_config = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_config.setObjectName("lineEdit_config")
        self.horizontalLayout_3.addWidget(self.lineEdit_config)
        self.BT_config = QtWidgets.QPushButton(self.layoutWidget2)
        self.BT_config.setObjectName("BT_config")
        self.horizontalLayout_3.addWidget(self.BT_config)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog_predict)
        self.layoutWidget3.setGeometry(QtCore.QRect(160, 210, 63, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_gpu = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_gpu.setObjectName("comboBox_gpu")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.comboBox_gpu.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_gpu)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog_predict)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 140, 441, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_model = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.horizontalLayout_5.addWidget(self.lineEdit_model)
        self.BT_model = QtWidgets.QPushButton(self.layoutWidget_2)
        self.BT_model.setObjectName("BT_model")
        self.horizontalLayout_5.addWidget(self.BT_model)

        self.retranslateUi(Dialog_predict)
        self.buttonBox.rejected.connect(Dialog_predict.reject)
        self.BT_input.clicked.connect(Dialog_predict.slot_input)
        self.BT_output.clicked.connect(Dialog_predict.slot_output)
        self.BT_config.clicked.connect(Dialog_predict.slot_config)
        self.buttonBox.accepted.connect(Dialog_predict.slot_done)
        self.BT_model.clicked.connect(Dialog_predict.slot_model)
        QtCore.QMetaObject.connectSlotsByName(Dialog_predict)

    def retranslateUi(self, Dialog_predict):
        _translate = QtCore.QCoreApplication.translate
        Dialog_predict.setWindowTitle(_translate("Dialog_predict", "Dialog"))
        self.label.setText(_translate("Dialog_predict", "input"))
        self.BT_input.setText(_translate("Dialog_predict", "Open"))
        self.label_2.setText(_translate("Dialog_predict", "output"))
        self.BT_output.setText(_translate("Dialog_predict", "Open"))
        self.label_3.setText(_translate("Dialog_predict", "config"))
        self.BT_config.setText(_translate("Dialog_predict", "Open"))
        self.label_4.setText(_translate("Dialog_predict", "GPU"))
        self.comboBox_gpu.setItemText(0, _translate("Dialog_predict", "0"))
        self.comboBox_gpu.setItemText(1, _translate("Dialog_predict", "1"))
        self.comboBox_gpu.setItemText(2, _translate("Dialog_predict", "2"))
        self.comboBox_gpu.setItemText(3, _translate("Dialog_predict", "3"))
        self.comboBox_gpu.setItemText(4, _translate("Dialog_predict", "4"))
        self.comboBox_gpu.setItemText(5, _translate("Dialog_predict", "5"))
        self.comboBox_gpu.setItemText(6, _translate("Dialog_predict", "6"))
        self.comboBox_gpu.setItemText(7, _translate("Dialog_predict", "7"))
        self.label_5.setText(_translate("Dialog_predict", "model"))
        self.BT_model.setText(_translate("Dialog_predict", "Open"))

